import type { Metadata } from 'next';
import getEnv from '@/util/getEnv';
import { ENV_PREFIX } from '@/constant';
import EnvProvider from '@/provider/env';
import Script from 'next/script'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  // for safty, only get HK01WEB env variables
  const env = Object.entries(getEnv()).reduce((acc: any, [key, value]) => {
    if (key.startsWith(ENV_PREFIX)) {
      acc[key] = value;
    }
    return acc
  }, {});

  return (
    <html>
      <head>
        <Script
          id="runtimeEnv"
          strategy="beforeInteractive"
        >{`window.${ENV_PREFIX} = ${JSON.stringify(env, null, 2)}`}</Script>
      </head>
      <body>
        <EnvProvider value={env}>
          {children}
        </EnvProvider>
      </body>
    </html>
  )
}
